server:
  port: 8070

application:
  version: AppVersion 1.0.0
  title: anjxxyi

spring:
  security:
    user:
      name: user
      password: 1234
    oauth2:
      client:
        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id
        registration:
          kakao:
            client-id: ad322ec159602f7ad6d8dc173161b9d2
            client-secret: eSEWdAaBtqukIGj2OO4v7XqPUegSkvEp
            client-authentication-method: client_secret_post
            redirect-uri: http://localhost:8070/login/oauth2/code/kakao
            authorization-grant-type: authorization_code
            client-name: kakao
            scope:
              - profile
              - account_email
          google:
            client-id: 423794899259-v1u4c59oie7dhmhmnbeuh2ta0fjun841.apps.googleusercontent.com
            client-secret: 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
            redirect-uri: http://localhost:8070/login/oauth2/code/google
            scope:
              - email
              - profile
  thymeleaf:
    cache: false
  sql:
    init:
      mode: always
      encoding: utf-8
  jpa:
    show-sql: true # java코드로 짠 sql을
    defer-datasource-initialization: true # data.sql 사용을 위해서 필수적으로 등록
    properties:
      hibernate:
        format_sql: true  # sql문 pretty하게 보여줌
        use_sql_comments: true
    generate-ddl: true   # true, false
    hibernate:
      ddl-auto: create    # create, create-drop, update, validate, none
  datasource:
    url: jdbc:mariadb://localhost:3306/mydb         # mariadb
    driver-class-name: org.mariadb.jdbc.Driver
    username: root
    password: 1234
  h2:
    console:
      path: /h2-console
      enabled: true
  mvc:
    view:
      prefix: /WEB-INF/view/
      suffix: .jsp
  devtools:
    livereload:
      enabled: true

#logging.level:
logging:
  level:
    org:
      hibernate:
        orm:
          jdbc:
            bind: trace
        SQL: debug
        type:
          decriptor:
    sql: trace

jwt:
  issuer: user1@abc.com
  secret_key: abcd